# Generated by Django 3.0.4 on 2021-10-27 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('public_private', models.CharField(max_length=3)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('place', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=2000)),
                ('submissionconnection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionconnection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
