# Generated by Django 3.0.4 on 2021-10-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0003_auto_20211029_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
