# Generated by Django 3.0.4 on 2021-10-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0004_auto_20211029_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.IntegerField(choices=[(11, '和食'), (12, '洋食'), (13, '中華'), (14, 'アジア'), (15, 'カレー'), (16, '焼肉'), (17, '鍋'), (18, '麺類'), (19, '軽食'), (20, 'スイーツ'), (21, '飲食'), (22, 'その他')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='public_private',
            field=models.IntegerField(choices=[(11, '公開'), (12, '非公開')]),
        ),
    ]
