# Generated by Django 3.0.4 on 2021-10-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0005_auto_20211030_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='talk',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
