# Generated by Django 3.0.4 on 2021-10-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0006_submission_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.IntegerField(choices=[(11, '和食'), (12, '洋食'), (13, '中華'), (14, 'アジア'), (15, 'カレー'), (16, '焼肉'), (17, '鍋'), (18, '麺類'), (19, '軽食'), (20, 'スイーツ'), (21, '飲食'), (22, 'その他')], null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='comment',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='public_private',
            field=models.IntegerField(choices=[(11, '公開'), (12, '非公開')], null=True),
        ),
    ]
