# Generated by Django 3.0.4 on 2021-10-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0007_auto_20211030_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='talk',
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.CharField(max_length=150)),
                ('threadconnection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threadconnection', to='cookapp.Submission')),
            ],
        ),
    ]
