# Generated by Django 3.0.4 on 2021-10-30 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0008_auto_20211030_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='threadconnection',
        ),
        migrations.AddField(
            model_name='thread',
            name='threadconnection_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threadconnection_image', to='cookapp.Submission'),
        ),
        migrations.AddField(
            model_name='thread',
            name='threadconnection_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threadconnection_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
