# Generated by Django 3.0.4 on 2021-11-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0010_auto_20211101_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends_request',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='cookapp.Friends'),
        ),
        migrations.AlterField(
            model_name='friends_request',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='cookapp.Friends'),
        ),
    ]
