# Generated by Django 3.0.4 on 2021-11-02 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0012_auto_20211103_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='from_user',
        ),
        migrations.AddField(
            model_name='friends',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='friends',
            name='to_user',
        ),
        migrations.AddField(
            model_name='friends',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
