# Generated by Django 3.0.4 on 2021-11-03 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0013_auto_20211103_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='to_user',
        ),
        migrations.AddField(
            model_name='friends',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friends',
            name='users',
            field=models.ManyToManyField(blank=True, default='users', related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
