# Generated by Django 3.0.4 on 2021-11-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0014_auto_20211103_1247'),
        ('cookapp', '0010_auto_20211102_1908'),
    ]

    operations = [
    ]
