# Generated by Django 3.2 on 2021-11-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0010_auto_20211102_1908'),
        ('cookapp', '0014_auto_20211103_1247'),
    ]

    operations = [
    ]
