# Generated by Django 3.0.4 on 2021-11-07 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0015_merge_20211107_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='users',
        ),
        migrations.AddField(
            model_name='friends',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
