# Generated by Django 3.0.4 on 2021-11-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0015_merge_0010_auto_20211102_1908_0014_auto_20211103_1247'),
        ('cookapp', '0016_auto_20211107_1920'),
    ]

    operations = [
    ]
