# Generated by Django 3.0.4 on 2021-11-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0017_merge_20211110_2032'),
        ('cookapp', '0017_merge_20211110_1959'),
    ]

    operations = [
    ]
