# Generated by Django 3.0.4 on 2021-11-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0015_merge_20211106_0757'),
        ('cookapp', '0018_alter_user_first_name'),
        ('cookapp', '0018_merge_20211114_1557'),
        ('cookapp', '0017_merge_20211109_0954'),
    ]

    operations = [
    ]
