# Generated by Django 3.0.4 on 2021-11-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0022_auto_20211124_2107'),
        ('cookapp', '0020_auto_20211123_0802'),
        ('cookapp', '0020_auto_20211124_1938'),
    ]

    operations = [
    ]
