# Generated by Django 3.0.4 on 2021-11-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0024_auto_20211125_0922'),
        ('cookapp', '0023_merge_20211125_1820'),
    ]

    operations = [
    ]
