# Generated by Django 3.0.4 on 2021-11-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0025_merge_20211128_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0)),
                ('submission_times', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_times', to='cookapp.Submission')),
            ],
        ),
    ]
