# Generated by Django 3.0.4 on 2021-11-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0026_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
