# Generated by Django 3.0.4 on 2021-12-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0019_merge_20211121_0213'),
        ('cookapp', '0027_auto_20211128_2225'),
    ]

    operations = [
    ]
