# Generated by Django 3.0.4 on 2021-11-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0027_auto_20211128_2225'),
        ('cookapp', '0019_merge_20211121_0213'),
    ]

    operations = [
    ]
