# Generated by Django 3.2.9 on 2021-12-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0019_merge_20211121_0213'),
        ('cookapp', '0027_auto_20211128_2225'),
    ]

    operations = [
    ]
