# Generated by Django 3.0.4 on 2021-12-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0030_auto_20211201_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
