# Generated by Django 3.2.9 on 2021-12-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0033_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
