# Generated by Django 3.0.4 on 2021-12-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0029_auto_20211129_0917'),
        ('cookapp', '0035_auto_20211204_0914'),
    ]

    operations = [
    ]
