# Generated by Django 3.2.9 on 2021-12-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0037_auto_20211204_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
