# Generated by Django 3.2 on 2021-12-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0028_merge_20211202_1908'),
        ('cookapp', '0037_auto_20211204_1927'),
    ]

    operations = [
    ]
