# Generated by Django 3.2.9 on 2021-12-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0038_alter_user_first_name'),
        ('cookapp', '0038_merge_20211209_1625'),
    ]

    operations = [
    ]
