# Generated by Django 3.2 on 2021-12-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0039_auto_20211210_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='welcomeロゴ.png', null=True, upload_to=''),
        ),
    ]
