# Generated by Django 3.2.9 on 2021-12-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0039_merge_20211209_1517'),
        ('cookapp', '0039_merge_20211209_1519'),
        ('cookapp', '0039_merge_20211209_1522'),
        ('cookapp', '0041_alter_user_icon'),
    ]

    operations = [
    ]
