# Generated by Django 3.2.9 on 2021-12-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0042_merge_20211210_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='グループ481 .png', null=True, upload_to=''),
        ),
    ]
