# Generated by Django 3.2.9 on 2021-12-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0029_auto_20211203_1304'),
        ('cookapp', '0042_merge_20211210_0218'),
    ]

    operations = [
    ]
