# Generated by Django 3.2.9 on 2021-12-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0043_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='グループ481.png', null=True, upload_to=''),
        ),
    ]
