# Generated by Django 3.2.9 on 2021-12-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0043_merge_20211210_0616'),
        ('cookapp', '0045_alter_user_icon'),
    ]

    operations = [
    ]
