# Generated by Django 3.2.9 on 2021-12-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0046_merge_0043_merge_20211210_0616_0045_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='メールアドレス'),
        ),
    ]
